<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>me.margueritedefrize.wecook</groupId>
  <artifactId>master</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>dto</module>
    <module>utils</module>
  </modules>

  <properties>
    <!-- JAVA -->
    <java.version>25</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <lombok.version>1.18.46</lombok.version>
    <junit.version>6.1.3</junit.version>
  </properties>
</project>
